language: objective-c
sudo: false
xcode_project: DKHelper/DKHelper.xcodeproj
xcode_scheme: DKHelper
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild test -project "DKHelper/DKHelper.xcodeproj" -scheme "DKHelper" -destination "platform=iOS Simulator,name=iPhone 6s" GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES | xcpretty

before_deploy:
  - carthage build --no-skip-current
  - carthage archive DKHelper
deploy:
  skip_cleanup: true
  provider: releases
  file: DKHelper.framework.zip
  api_key:
    secure: Q4A/AaeXS9N6JL9k5WS1PDPnMGoo1qmD5wlbMEu9H8ZQQhOQKLY/x8xQbi/82eyfXWyTgjVxgscH19atzYLr9jogmZj2v0nNASqjql/bNxvu7VBKY0N6P+sQU4cCoQw+3oqhP4U+owMyvabfV7sWlvpYa3GPYGVNAtFfotsqpCkvB0COmggCIddU2LS6pl+hg5QgP195ldBBAQW+z5PO5Wmq8Gvd88IG330r2jslCz+3O38qwJIZSZnfQuG9LDJVEitp67S1y9AAn7Wp5oPNRJ6nOwkI4bgGxnLJDwDB13DEAvG8sJtEqBV8gBx0KYJTQNqJTYKLHy102UG/WBBcRNTuIaookEvf8RHzbFBnX9mGK5Q2jF9G+q8r7zjw1sq1DghknxX9m8M0GZLner7J4A36T4BtHoVzogPUIIsN7moEDbgJY9Zu2oR+JFl675EB3rVuhR0EnbZUqV1u1Jo3AsOBu+ZdnnPgc4FD2JxZODOc2kzw/uAY0HcgUcqz4sR7e31Ozs8zizUM268FXMohryoMotrCfREM3AIPQsyBf9Uh9ZGpCNyrk9GiDT+wgSrSceiFOsQqsPbCDp8ED7lp3Q+7WttOXIc9fZ8tPFsiA0jyxLF6PqxUEYBaGAy6GdFC1zh7URQ9Iy6ERdzXF/cVunLIVITraij6EwY8+G3pUrE=
  on:
    repo: kevindelord/DKHelper
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
