language: objective-c
sudo: false

# osx_image: xcode8.2
# xcode_sdk: iphonesimulator10.1
# env:
#   global:
#     - FRAMEWORK_NAME=DKHelper
#     - WORKSPACE=DKHelper.xcworkspace
#     - SCHEME=DKHelper
#     - SKD=iphonesimulator10.1
#     - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"
#     - XCARGS="GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES"

# before_install:
#   - brew update
#   - brew outdated carthage || brew upgrade carthage
# script:
#   - set -o pipefail
#   - xcodebuild -version
#   - xcodebuild -showsdks
#   - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release "$XCARGS" test | xcpretty

# xcodebuild -workspace DKHelper.xcworkspace -scheme DKHelper -sdk "iphonesimulator10.2" -destination "platform=iOS Simulator,id=767716CA-F49B-480B-86F0-4E6E9D773736,OS=10.2" -configuration Debug GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty


xcode_project: DKHelper.xcworkspace
xcode_scheme: DKHelper
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -workspace DKHelper.xcworkspace -scheme "DKHelper" -destination "platform=iOS Simulator,name=iPhone 6s"

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  skip_cleanup: true
  provider: releases
  file: $FRAMEWORK_NAME.framework.zip
  api_key:
    secure: Q4A/AaeXS9N6JL9k5WS1PDPnMGoo1qmD5wlbMEu9H8ZQQhOQKLY/x8xQbi/82eyfXWyTgjVxgscH19atzYLr9jogmZj2v0nNASqjql/bNxvu7VBKY0N6P+sQU4cCoQw+3oqhP4U+owMyvabfV7sWlvpYa3GPYGVNAtFfotsqpCkvB0COmggCIddU2LS6pl+hg5QgP195ldBBAQW+z5PO5Wmq8Gvd88IG330r2jslCz+3O38qwJIZSZnfQuG9LDJVEitp67S1y9AAn7Wp5oPNRJ6nOwkI4bgGxnLJDwDB13DEAvG8sJtEqBV8gBx0KYJTQNqJTYKLHy102UG/WBBcRNTuIaookEvf8RHzbFBnX9mGK5Q2jF9G+q8r7zjw1sq1DghknxX9m8M0GZLner7J4A36T4BtHoVzogPUIIsN7moEDbgJY9Zu2oR+JFl675EB3rVuhR0EnbZUqV1u1Jo3AsOBu+ZdnnPgc4FD2JxZODOc2kzw/uAY0HcgUcqz4sR7e31Ozs8zizUM268FXMohryoMotrCfREM3AIPQsyBf9Uh9ZGpCNyrk9GiDT+wgSrSceiFOsQqsPbCDp8ED7lp3Q+7WttOXIc9fZ8tPFsiA0jyxLF6PqxUEYBaGAy6GdFC1zh7URQ9Iy6ERdzXF/cVunLIVITraij6EwY8+G3pUrE=
  on:
    repo: kevindelord/DKHelper
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
