language: objective-c
osx_image: xcode7.3
xcode_workspace: DKHelper.xcworkspace
xcode_scheme: DKHelper
xcode_sdk: iphonesimulator9.3
sudo: false
env:
  global: 
    - FRAMEWORK_NAME=DKHelper
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  # provider: releases
  # api_key: a337ae160bd51178c9890b3bfa175d0ea514b683
  #file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: kevindelord/DKHelper
    tags: true




# env:
#   global:
#     - LC_CTYPE=en_US.UTF-8
#     - LANG=en_US.UTF-8
#     - WORKSPACE=DKHelper.xcworkspace
#     - FRAMEWORK_SCHEME="DKHelper"
#     - IOS_SDK=iphonesimulator9.3
#   matrix:
#     - DESTINATION="OS=9.3,name=iPhone 6S Plus"     SCHEME="$FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
# script:
#   - set -o pipefail
#   - xcodebuild -version
#   - xcodebuild -showsdks

#   # Build Framework in Debug and Run Tests if specified
#   - if [ $RUN_TESTS == "YES" ]; then
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;
#     else
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug build | xcpretty -c;
#     fi

#   # Build Framework in ReleaseTest and Run Tests if specified
#   - if [ $RUN_TESTS == "YES" ]; then
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
#     else
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
#     fi


# xcodebuild -workspace DKHelper.xcworkspace -scheme DKHelper -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" build test GCC_GENERATE_TEST_COVERAGE_FILES=YES
# xcodebuild -workspace DKHelper.xcworkspace -scheme DKHelper -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" build test GCC_GENERATE_TEST_COVERAGE_FILES=YES